version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3002"
    depends_on: 
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: affanmaulana
      POSTGRES_PASSWORD: 12qwaszx
      POSTGRES_DB: bunchat
      TZ: Asia/Jakarta
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
